### ISSUE TITLE
Bug in lhefevent.hpp

### ISSUE THREAD

**Issue by flokoenig** [benoleary/LesHouchesParserClasses_CPP#1]
Hi,

while using your code to parse lhe files I found a bug in line 151 of LHPC/include/LesHouchesEventFileClasses/LhefEvent.hpp

It says 

```
inline double
LhefEvent::getEventWeight() const
{
  return eventId;
}
```

but it should be 

return evenWeight;

Cheers,
Florian König

**Comment by benoleary** [comment]
Oh, thank you! I will deal with this soon, but not tomorrow as I am travelling.

**Comment by benoleary** [comment]
Fixed. Thank you again for pointing this out! I will update the tarball on HepForge now too.
